import { describe, expect, it } from 'vitest';
import { Levenshtein, OSA } from './rapidfuzz';
import fixture from './rapidfuzz-parity.fixture.json';

// Expected values generated by real RapidFuzz (see tools/benchmarks/generate-rapidfuzz-parity-fixture.py,
// run with `uv run --with rapidfuzz==3.14.6 ...`; RapidFuzz itself is never a project dependency).
// Cases: the 929 medication-name cases from the 2026-09-24 RapidFuzz experiment (existing 162-case
// regression set plus deterministic corpus mutations), 300 exact-name self-pairs, a handful of
// boundary cases (empty strings, the 64/65 code-unit bit-parallel/DP-fallback edge), and random
// Cyrillic/Latin pairs.
interface ParityCase {
  readonly id: string;
  readonly a: string;
  readonly b: string;
  readonly osaDistance: number;
  readonly osaNormalizedSimilarity: number;
  readonly levenshteinDistance: number;
  readonly levenshteinNormalizedSimilarity: number;
}

const cases = fixture.cases as readonly ParityCase[];

describe(`rapidfuzz parity (${fixture.rapidfuzzVersion}, ${cases.length} cases)`, () => {
  it('covers the full experiment case set plus random/boundary pairs', () => {
    expect(cases.length).toBeGreaterThan(1700);
    expect(cases.some((c) => c.id.startsWith('medication.'))).toBe(true);
    expect(cases.filter((c) => c.id.startsWith('medication.')).length).toBe(929);
    expect(cases.filter((c) => c.id.startsWith('exact-control.')).length).toBe(300);
  });

  it.each(cases)('OSA distance/similarity matches RapidFuzz for $id', (testCase) => {
    expect(OSA.distance(testCase.a, testCase.b)).toBe(testCase.osaDistance);
    expect(OSA.normalizedSimilarity(testCase.a, testCase.b)).toBeCloseTo(
      testCase.osaNormalizedSimilarity,
      12,
    );
  });

  it.each(cases)('Levenshtein distance/similarity matches RapidFuzz for $id', (testCase) => {
    expect(Levenshtein.distance(testCase.a, testCase.b)).toBe(testCase.levenshteinDistance);
    expect(Levenshtein.normalizedSimilarity(testCase.a, testCase.b)).toBeCloseTo(
      testCase.levenshteinNormalizedSimilarity,
      12,
    );
  });
});
