/**
 * The pregnancy / lactation / age-limit index asset (SAFE1): its shape, its validation at the
 * package boundary and the lookups the search card uses. Generated by
 * `scripts/build-medication-safety.ts`; nobody edits it by hand.
 *
 * Like the drug-interaction index (INT1) it holds NO instruction text: for every indexed
 * instruction it holds offsets into the canonical text of a section (see
 * `drug-interactions/interaction-text.ts`) plus a short checksum of that text. The quoted text is
 * always read from the installed document, with that document's own provenance.
 */
import {
  compareRankedDocuments,
  INSTRUCTION_KINDS,
  SECTION_CHECKSUM_LENGTH,
  SECTION_ID_PREFIX,
} from '@/features/drug-interactions/interaction-index';

export const SAFETY_INDEX_SCHEMA_VERSION = 1;
/** Instructions kept per МНН card: the best one of each of the most common dosage forms. */
export const SAFETY_DOCUMENTS_PER_CARD = 5;

/** Where in the instruction a sentence stands. */
export const ORIGIN_PREGNANCY_SECTION = 0;
export const ORIGIN_CONTRAINDICATIONS = 1;
export const ORIGIN_CAUTION = 2;
export const ORIGIN_SPECIAL = 3;
export const ORIGIN_DOSAGE = 4;
export const ORIGIN_OTHER = 5;
export const ORIGIN_INDICATIONS = 6;
const ORIGIN_COUNT = 7;

/** `flags` of a sentence entry: topic (2 bits), origin (3 bits), dosage forms named (8 bits). */
export function packFlags(topic: number, origin: number, forms: number): number {
  return topic | (origin << 2) | (forms << 5);
}
export function flagsTopic(flags: number): number {
  return flags & 3;
}
export function flagsOrigin(flags: number): number {
  return (flags >> 2) & 7;
}
export function flagsForms(flags: number): number {
  return flags >> 5;
}

/** Codes of a limit inside an age-limit entry. */
export const LIMIT_AGE_BELOW = 0;
export const LIMIT_AGE_FROM = 1;
export const LIMIT_AGE_RANGE = 2;
export const LIMIT_WEIGHT_BELOW = 3;
export const LIMIT_WEIGHT_FROM = 4;
export const LIMIT_WEIGHT_RANGE = 5;
export const LIMIT_CATEGORY = 6;
const LIMIT_CODE_COUNT = 7;
/** Numbers per limit inside an entry: match start, match end, code, lower, upper. */
export const LIMIT_WIDTH = 5;
/** Entry header: section index, start, end, flags. */
const ENTRY_HEADER = 4;

export interface SafetyDocument {
  /** Indexes into `cards`: the МНН cards the document's registrations belong to. */
  readonly c: readonly number[];
  /** Index into `modules`. */
  readonly m: number;
  /** Trade name of the product, as the registry writes it. */
  readonly t: string | null;
  /** Index into `INSTRUCTION_KINDS`. */
  readonly k: number;
  /** 1 for a holder's own site, 0 for a ГРЛС file. */
  readonly s: 0 | 1;
  /** Dosage form of the product, as the document's metadata states it. */
  readonly f: string | null;
  /** 1 when the instruction has a pregnancy / lactation section. */
  readonly p: 0 | 1;
  /** 1 when at least one age or weight limit was found. */
  readonly a: 0 | 1;
  /** How many instructions of the same dosage form the card has: the common form is read first. */
  readonly n: number;
  /** `[section id without «section.», checksum]`. */
  readonly sec: readonly (readonly [string, string])[];
  /** Pregnancy / lactation sentences: `[section, start, end, flags, matchStart, matchEnd]`. */
  readonly pl: readonly (readonly number[])[];
  /** Age limits: `[section, start, end, flags, (matchStart, matchEnd, code, lower, upper)+]`. */
  readonly ag: readonly (readonly number[])[];
}

export interface SafetyIndexAsset {
  readonly schemaVersion: typeof SAFETY_INDEX_SCHEMA_VERSION;
  readonly basis: {
    readonly modules: readonly {
      readonly id: string;
      readonly version: string;
      readonly sha256: string;
    }[];
  };
  readonly modules: readonly string[];
  /** Slugs of the ЕСКЛП МНН cards (`esklp.mnn.<slug>`). */
  readonly cards: readonly string[];
  readonly documents: Readonly<Record<string, SafetyDocument>>;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function fail(message: string): never {
  throw new Error(`Medication-safety index: ${message}`);
}

function isIndex(value: unknown, limit: number): value is number {
  return Number.isInteger(value) && (value as number) >= 0 && (value as number) < limit;
}

function parseEntries(
  id: string,
  value: unknown,
  sectionCount: number,
  kind: 'pl' | 'ag',
): readonly (readonly number[])[] {
  if (!Array.isArray(value)) fail(`document ${id} has no ${kind}`);
  return (value as readonly unknown[]).map((entry) => {
    if (!Array.isArray(entry) || entry.some((item) => !Number.isInteger(item))) {
      fail(`document ${id} has a malformed ${kind} entry`);
    }
    const numbers = entry as readonly number[];
    const [section, start, end, flags] = numbers;
    if (
      !isIndex(section, sectionCount) ||
      start === undefined ||
      end === undefined ||
      flags === undefined ||
      start < 0 ||
      end <= start ||
      flagsOrigin(flags) >= ORIGIN_COUNT
    ) {
      fail(`document ${id} has an invalid ${kind} range`);
    }
    if (kind === 'pl') {
      if (numbers.length !== ENTRY_HEADER + 2) fail(`document ${id} has a malformed pl entry`);
    } else {
      const rest = numbers.length - ENTRY_HEADER;
      if (rest <= 0 || rest % LIMIT_WIDTH !== 0) fail(`document ${id} has a malformed ag entry`);
      for (let at = ENTRY_HEADER; at < numbers.length; at += LIMIT_WIDTH) {
        if (!isIndex(numbers[at + 2], LIMIT_CODE_COUNT))
          fail(`document ${id} has an unknown limit code`);
      }
    }
    return numbers;
  });
}

function parseDocument(
  id: string,
  value: unknown,
  counts: { cards: number; modules: number },
): SafetyDocument {
  if (!isRecord(value)) fail(`document ${id} is not an object`);
  const { c, m, t, k, s, f, p, a, n, sec, pl, ag } = value;
  if (!Array.isArray(c) || c.some((item) => !isIndex(item, counts.cards))) {
    fail(`document ${id} has an invalid card`);
  }
  if (!isIndex(m, counts.modules)) fail(`document ${id} has no module`);
  if (!isIndex(k, INSTRUCTION_KINDS.length)) fail(`document ${id} has an unknown kind`);
  if (s !== 0 && s !== 1) fail(`document ${id} has an unknown source class`);
  if (p !== 0 && p !== 1) fail(`document ${id} has no pregnancy-section flag`);
  if (a !== 0 && a !== 1) fail(`document ${id} has no age-limit flag`);
  if (!Number.isInteger(n) || (n as number) < 1) fail(`document ${id} has no form count`);
  if (t !== null && typeof t !== 'string') fail(`document ${id} has an invalid trade name`);
  if (f !== null && typeof f !== 'string') fail(`document ${id} has an invalid dosage form`);
  if (!Array.isArray(sec)) fail(`document ${id} has no sections`);
  const sections = (sec as readonly unknown[]).map((entry) => {
    if (
      !Array.isArray(entry) ||
      entry.length !== 2 ||
      entry.some((item) => typeof item !== 'string')
    ) {
      fail(`document ${id} has a malformed section entry`);
    }
    return entry as unknown as readonly [string, string];
  });
  return {
    c: c as readonly number[],
    m,
    t: t as string | null,
    k,
    s,
    f: f as string | null,
    p,
    a,
    n: n as number,
    sec: sections,
    pl: parseEntries(id, pl, sections.length, 'pl'),
    ag: parseEntries(id, ag, sections.length, 'ag'),
  };
}

/** Checks the asset's shape once; a malformed asset is an error, never a silently empty index. */
export function parseSafetyIndex(value: unknown): SafetyIndexAsset {
  if (!isRecord(value)) fail('not an object');
  if (value['schemaVersion'] !== SAFETY_INDEX_SCHEMA_VERSION) fail('unsupported schema version');
  const { basis, modules, cards, documents } = value;
  if (!isRecord(basis)) fail('basis is missing');
  if (!Array.isArray(modules) || modules.some((item) => typeof item !== 'string')) {
    fail('modules is not a list of strings');
  }
  if (!Array.isArray(cards) || cards.some((item) => typeof item !== 'string')) {
    fail('cards is not a list of strings');
  }
  if (!isRecord(documents)) fail('documents is not an object');
  const counts = { cards: cards.length, modules: modules.length };
  const parsed: Record<string, SafetyDocument> = {};
  for (const [id, document] of Object.entries(documents))
    parsed[id] = parseDocument(id, document, counts);
  const modulesBasis = basis['modules'];
  return {
    schemaVersion: SAFETY_INDEX_SCHEMA_VERSION,
    basis: {
      modules: Array.isArray(modulesBasis)
        ? (modulesBasis as readonly { id: string; version: string; sha256: string }[])
        : [],
    },
    modules: modules as readonly string[],
    cards: cards as readonly string[],
    documents: parsed,
  };
}

/**
 * Which instruction of a card to read first: one with its own pregnancy / lactation section, then
 * the card's most common dosage form, one with an age limit, a ГРЛС file before a holder's site, a
 * professional text before a leaflet.
 */
export function compareSafetyDocuments(
  left: { readonly id: string } & Pick<SafetyDocument, 'p' | 'a' | 's' | 'k' | 'n'>,
  right: { readonly id: string } & Pick<SafetyDocument, 'p' | 'a' | 's' | 'k' | 'n'>,
): number {
  return (
    right.p - left.p ||
    right.n - left.n ||
    right.a - left.a ||
    compareRankedDocuments(
      { id: left.id, x: 0, s: left.s, k: left.k },
      { id: right.id, x: 0, s: right.s, k: right.k },
    )
  );
}

export interface SafetyIndex {
  readonly asset: SafetyIndexAsset;
  readonly cardBySlug: ReadonlyMap<string, number>;
  /** Card index → its instructions, best first. */
  readonly documentsOfCard: ReadonlyMap<number, readonly string[]>;
}

export function createSafetyIndex(asset: SafetyIndexAsset): SafetyIndex {
  const cardBySlug = new Map<string, number>();
  asset.cards.forEach((slug, index) => {
    cardBySlug.set(slug, index);
  });
  const documentsOfCard = new Map<number, string[]>();
  for (const [id, document] of Object.entries(asset.documents)) {
    for (const card of document.c) {
      const list = documentsOfCard.get(card);
      if (list) list.push(id);
      else documentsOfCard.set(card, [id]);
    }
  }
  const documents = asset.documents;
  for (const list of documentsOfCard.values()) {
    list.sort((left, right) => {
      const a = documents[left];
      const b = documents[right];
      if (!a || !b) return left.localeCompare(right);
      return compareSafetyDocuments({ id: left, ...a }, { id: right, ...b });
    });
  }
  return { asset, cardBySlug, documentsOfCard };
}

/** One sentence the index points at, with the section it stands in. */
export interface SafetySentence {
  readonly documentId: string;
  /** Full section id and the checksum of its canonical text. */
  readonly section: readonly [string, string];
  readonly start: number;
  readonly end: number;
  readonly flags: number;
  /** The words that made it a hit: `[start, end)` of the first and the last match. */
  readonly matchStart: number;
  readonly matchEnd: number;
}

export type LimitCode =
  | typeof LIMIT_AGE_BELOW
  | typeof LIMIT_AGE_FROM
  | typeof LIMIT_AGE_RANGE
  | typeof LIMIT_WEIGHT_BELOW
  | typeof LIMIT_WEIGHT_FROM
  | typeof LIMIT_WEIGHT_RANGE
  | typeof LIMIT_CATEGORY;

/** One limit found in a sentence: its bounds and the words it was read from. */
export interface IndexedLimit {
  readonly matchStart: number;
  readonly matchEnd: number;
  readonly code: LimitCode;
  /** Days (age), tenths of kg (weight) or the category index (`AGE_CATEGORIES`). */
  readonly lower: number;
  readonly upper: number;
}

export interface AgeSentence {
  readonly documentId: string;
  readonly section: readonly [string, string];
  readonly start: number;
  readonly end: number;
  readonly flags: number;
  readonly limits: readonly IndexedLimit[];
}

function sectionOf(document: SafetyDocument, index: number): readonly [string, string] | null {
  const entry = document.sec[index];
  return entry ? [`${SECTION_ID_PREFIX}${entry[0]}`, entry[1]] : null;
}

/** The pregnancy / lactation sentences of an instruction, in reading order. */
export function pregnancySentences(
  index: SafetyIndex,
  documentId: string,
): readonly SafetySentence[] {
  const document = index.asset.documents[documentId];
  if (!document) return [];
  const sentences: SafetySentence[] = [];
  for (const entry of document.pl) {
    const [section, start, end, flags, matchStart, matchEnd] = entry as readonly number[];
    const sectionEntry = sectionOf(document, section ?? -1);
    if (!sectionEntry || start === undefined || end === undefined || flags === undefined) continue;
    sentences.push({
      documentId,
      section: sectionEntry,
      start,
      end,
      flags,
      matchStart: matchStart ?? start,
      matchEnd: matchEnd ?? end,
    });
  }
  return sentences;
}

/** The sentences of an instruction that state an age or weight limit, in reading order. */
export function ageSentences(index: SafetyIndex, documentId: string): readonly AgeSentence[] {
  const document = index.asset.documents[documentId];
  if (!document) return [];
  const sentences: AgeSentence[] = [];
  for (const entry of document.ag) {
    const [section, start, end, flags] = entry as readonly number[];
    const sectionEntry = sectionOf(document, section ?? -1);
    if (!sectionEntry || start === undefined || end === undefined || flags === undefined) continue;
    const limits: IndexedLimit[] = [];
    for (let at = ENTRY_HEADER; at + LIMIT_WIDTH <= entry.length; at += LIMIT_WIDTH) {
      limits.push({
        matchStart: entry[at] ?? start,
        matchEnd: entry[at + 1] ?? end,
        code: (entry[at + 2] ?? 0) as LimitCode,
        lower: entry[at + 3] ?? 0,
        upper: entry[at + 4] ?? 0,
      });
    }
    sentences.push({ documentId, section: sectionEntry, start, end, flags, limits });
  }
  return sentences;
}

export { SECTION_CHECKSUM_LENGTH };
