import { describe, expect, it } from 'vitest';
import type { EcgLeadName } from './ecg-model-contract';
import { evaluateEcgSt } from './ecg-st';
import type { EcgAdultAgeBand, EcgSex } from './ecg-st-criteria';
import sample from './fixtures/ptbxl-plus-st-sample.json';

/**
 * Fixture: GE 12SL ST amplitude at the J point for 25 adult fold-10 records, generated by
 * tools/benchmarks/src/evaluate-ecg-st-ptbxl.ts. Source: PTB-XL 1.0.3 (Wagner et al., Sci Data
 * 2020) and PTB-XL+ 1.0.1 (Strodthoff et al., Sci Data 2023), PhysioNet, CC BY 4.0.
 */
interface SampleRecord {
  readonly ecgId: number;
  readonly sex: EcgSex;
  readonly ageBand: EcgAdultAgeBand;
  readonly qrsMs?: number;
  readonly labels: readonly string[];
  readonly stMv: Readonly<Record<EcgLeadName, number>>;
}

const records = sample.records as readonly SampleRecord[];

function findingIds(record: SampleRecord): string {
  const result = evaluateEcgSt({
    measurement: {
      leads: Object.entries(record.stMv).map(([lead, stMv]) => ({
        lead: lead as EcgLeadName,
        stMv,
        region: lead,
        edited: false,
      })),
      missing: {},
    },
    sex: record.sex,
    ageBand: record.ageBand,
    ...(record.qrsMs === undefined ? {} : { qrsMs: record.qrsMs }),
  });
  return result.findings.map((finding) => finding.id).join('+') || 'none';
}

// Regression snapshot of rule output per PTB-XL record; see the ST entry in
// docs/state/ecg-research-log.md for why these are agreement checks, not clinical accuracy.
const EXPECTED: Readonly<Record<number, string>> = {
  9: 'none',
  38: 'none',
  40: 'st-depression',
  57: 'none',
  59: 'none',
  75: 'none',
  76: 'none',
  79: 'none',
  271: 'st-depression',
  274: 'st-depression',
  318: 'st-depression',
  514: 'st-elevation+st-depression+st-reciprocal-inferior-lateral',
  534: 'st-elevation+st-depression',
  569: 'st-depression',
  756: 'st-depression',
  765: 'st-depression',
  861: 'none',
  947: 'st-elevation+st-depression',
  968: 'st-depression',
  1061: 'st-elevation',
  1307: 'st-elevation',
  2281: 'st-elevation+st-reciprocal-precordial-inferior',
  4059: 'none',
  4822: 'st-depression',
  10061: 'st-depression',
};

describe('ST rules on PTB-XL+ GE 12SL measurements', () => {
  it('keeps the per-record findings of the attributed 25-record sample', () => {
    expect(records).toHaveLength(Object.keys(EXPECTED).length);
    for (const record of records)
      expect([record.ecgId, findingIds(record)]).toEqual([record.ecgId, EXPECTED[record.ecgId]]);
  });

  it('does not flag sub-threshold PTB-XL «non-specific ST elevation» (STE_) as elevation', () => {
    const nonSpecific = records.filter((record) => record.labels.includes('STE_'));
    expect(nonSpecific.length).toBeGreaterThan(0);
    for (const record of nonSpecific) expect(findingIds(record)).not.toContain('st-elevation');
  });

  it('leaves most plain NORM records without ST findings', () => {
    const normal = records.filter(
      (record) => record.labels.includes('NORM') && record.labels.length <= 2,
    );
    const quiet = normal.filter((record) => findingIds(record) === 'none');
    expect(quiet.length / normal.length).toBeGreaterThanOrEqual(0.85);
  });
});
