/**
 * The drug-interaction index asset (INT1): its shape, its validation at the package boundary and the
 * lookups the tool and the search entry use. The asset is generated by
 * `scripts/build-drug-interactions.ts`; nobody edits it by hand.
 *
 * It holds NO instruction text. For every instruction document that is searched it holds the
 * sentences (as offsets into a section's canonical text, see `interaction-text.ts`) that name a
 * substance or a drug class, so the quoted text is always read from the installed document and
 * carries that document's own provenance.
 */

export const INTERACTION_INDEX_SCHEMA_VERSION = 1;

/** `documentKind` of an instruction, as the asset stores it (index = rank, best first). */
export const INSTRUCTION_KINDS = ['ohlp', 'national-instruction', 'unknown', 'leaflet'] as const;
export type IndexedInstructionKind = (typeof INSTRUCTION_KINDS)[number];

/** `[card id without «esklp.mnn.», ATC codes, substance target indexes]`. */
export type AssetCard = readonly [
  slug: string,
  atcCodes: readonly string[],
  substances: readonly number[],
];

/** Section ids are `section.<hex>`; the asset keeps the part after the dot. */
export const SECTION_ID_PREFIX = 'section.';
/** Hex digits of a section's checksum kept in the asset: enough to notice another edition. */
export const SECTION_CHECKSUM_LENGTH = 4;

/** Instruction documents kept per card: the best ones by `compareRankedDocuments`. */
export const DOCUMENTS_PER_CARD = 3;

export interface RankedDocument {
  readonly id: string;
  /** 1 when the instruction has its own interaction section. */
  readonly x: number;
  readonly s: number;
  readonly k: number;
}

/**
 * Which of a card's instructions to read first: one with its own interaction section, a ГРЛС file
 * before a holder's own site, a professional text (ОХЛП, instruction) before a leaflet.
 */
export function compareRankedDocuments(left: RankedDocument, right: RankedDocument): number {
  return (
    right.x - left.x || left.s - right.s || left.k - right.k || left.id.localeCompare(right.id)
  );
}

export interface AssetDocument {
  /** Indexes into `cards`: the МНН cards the document's registrations belong to. */
  readonly c: readonly number[];
  /** Index into `modules`: the instruction module that holds the document. */
  readonly m: number;
  /** Trade name of the product, as the registry writes it. */
  readonly t: string | null;
  /** Index into `INSTRUCTION_KINDS`. */
  readonly k: number;
  /** 1 for a holder's own site, 0 for a ГРЛС file. */
  readonly s: 0 | 1;
  /** 1 when the instruction has its own «Взаимодействие с другими лекарственными средствами» section. */
  readonly x: 0 | 1;
  /** `[section id without «section.», checksum of the section's canonical text]`. */
  readonly sec: readonly (readonly [string, string])[];
  /** `[section index, start, end, flags, ...target indexes]`. */
  readonly sp: readonly (readonly number[])[];
}

export interface InteractionIndexAsset {
  readonly schemaVersion: typeof INTERACTION_INDEX_SCHEMA_VERSION;
  readonly basis: {
    readonly atc: { readonly version: string; readonly publishDate: string };
    readonly modules: readonly {
      readonly id: string;
      readonly version: string;
      readonly sha256: string;
    }[];
  };
  /** `s:<substance key>` or `c:<ATC code>`. */
  readonly targets: readonly string[];
  readonly cards: readonly AssetCard[];
  readonly modules: readonly string[];
  readonly documents: Readonly<Record<string, AssetDocument>>;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function fail(message: string): never {
  throw new Error(`Drug-interaction index: ${message}`);
}

function stringArray(value: unknown, what: string): readonly string[] {
  if (!Array.isArray(value) || value.some((item) => typeof item !== 'string')) {
    fail(`${what} is not a list of strings`);
  }
  return value as readonly string[];
}

function indexArray(value: unknown, what: string, limit: number): readonly number[] {
  if (
    !Array.isArray(value) ||
    value.some(
      (item) => !Number.isInteger(item) || (item as number) < 0 || (item as number) >= limit,
    )
  ) {
    fail(`${what} holds an index outside 0..${limit - 1}`);
  }
  return value as readonly number[];
}

function parseCard(value: unknown, targetCount: number): AssetCard {
  if (!Array.isArray(value) || value.length !== 3) fail('a card is not [slug, atc, substances]');
  const [slug, atc, substances] = value as readonly unknown[];
  if (typeof slug !== 'string' || slug === '') fail('a card has no id');
  return [
    slug,
    stringArray(atc, 'card ATC codes'),
    indexArray(substances, 'card substances', targetCount),
  ];
}

function parseDocument(
  id: string,
  value: unknown,
  counts: { cards: number; modules: number; targets: number },
): AssetDocument {
  if (!isRecord(value)) fail(`document ${id} is not an object`);
  const { c, m, t, k, s, x, sec, sp } = value;
  if (!Number.isInteger(m) || (m as number) < 0 || (m as number) >= counts.modules) {
    fail(`document ${id} has no module`);
  }
  if (!Number.isInteger(k) || (k as number) < 0 || (k as number) >= INSTRUCTION_KINDS.length) {
    fail(`document ${id} has an unknown kind`);
  }
  if (s !== 0 && s !== 1) fail(`document ${id} has an unknown source class`);
  if (x !== 0 && x !== 1) fail(`document ${id} has no interaction-section flag`);
  if (t !== null && typeof t !== 'string') fail(`document ${id} has an invalid trade name`);
  if (!Array.isArray(sec)) fail(`document ${id} has no sections`);
  const sections = (sec as readonly unknown[]).map((entry) => {
    if (
      !Array.isArray(entry) ||
      entry.length !== 2 ||
      entry.some((item) => typeof item !== 'string')
    ) {
      fail(`document ${id} has a malformed section entry`);
    }
    return entry as unknown as readonly [string, string];
  });
  if (!Array.isArray(sp)) fail(`document ${id} has no sentences`);
  const spans = (sp as readonly unknown[]).map((entry) => {
    if (!Array.isArray(entry) || entry.length < 5) fail(`document ${id} has a malformed sentence`);
    const [section, start, end, flags, ...targets] = entry as readonly unknown[];
    if (
      !Number.isInteger(section) ||
      (section as number) < 0 ||
      (section as number) >= sections.length ||
      !Number.isInteger(start) ||
      !Number.isInteger(end) ||
      (start as number) < 0 ||
      (end as number) <= (start as number) ||
      !Number.isInteger(flags) ||
      (flags as number) <= 0
    ) {
      fail(`document ${id} has an invalid sentence range`);
    }
    indexArray(targets, `a sentence of ${id}`, counts.targets);
    return entry as readonly number[];
  });
  return {
    c: indexArray(c, `document ${id} cards`, counts.cards),
    m: m as number,
    t: t as string | null,
    k: k as number,
    s: s,
    x: x,
    sec: sections,
    sp: spans,
  };
}

/** Checks the asset's shape once; a malformed asset is an error, never a silently empty index. */
export function parseInteractionIndex(value: unknown): InteractionIndexAsset {
  if (!isRecord(value)) fail('not an object');
  if (value['schemaVersion'] !== INTERACTION_INDEX_SCHEMA_VERSION)
    fail('unsupported schema version');
  const { basis, targets, cards, modules, documents } = value;
  if (!isRecord(basis) || !isRecord(basis['atc'])) fail('basis is missing');
  const atc = basis['atc'];
  if (typeof atc['version'] !== 'string' || typeof atc['publishDate'] !== 'string') {
    fail('ATC basis is missing');
  }
  const targetList = stringArray(targets, 'targets');
  for (const target of targetList) {
    if (!/^(?:s:.+|c:[A-Z][0-9A-Z]*)$/u.test(target)) fail(`target «${target}» is malformed`);
  }
  if (!Array.isArray(cards)) fail('cards is not a list');
  const moduleList = stringArray(modules, 'modules');
  if (!isRecord(documents)) fail('documents is not an object');
  const parsedCards = (cards as readonly unknown[]).map((card) =>
    parseCard(card, targetList.length),
  );
  const counts = {
    cards: parsedCards.length,
    modules: moduleList.length,
    targets: targetList.length,
  };
  const parsedDocuments: Record<string, AssetDocument> = {};
  for (const [id, document] of Object.entries(documents)) {
    parsedDocuments[id] = parseDocument(id, document, counts);
  }
  const modulesBasis = basis['modules'];
  return {
    schemaVersion: INTERACTION_INDEX_SCHEMA_VERSION,
    basis: {
      atc: { version: atc['version'], publishDate: atc['publishDate'] },
      modules: Array.isArray(modulesBasis)
        ? (modulesBasis as readonly { id: string; version: string; sha256: string }[])
        : [],
    },
    targets: targetList,
    cards: parsedCards,
    modules: moduleList,
    documents: parsedDocuments,
  };
}

/** Indexes the app builds once after parsing. */
export interface InteractionIndex {
  readonly asset: InteractionIndexAsset;
  readonly cardBySlug: ReadonlyMap<string, number>;
  /** Card index → its instruction documents, best first. */
  readonly documentsOfCard: ReadonlyMap<number, readonly string[]>;
  /** Target index → card indexes that hold that substance. */
  readonly cardsOfSubstance: ReadonlyMap<number, readonly number[]>;
}

function compareDocuments(asset: InteractionIndexAsset, leftId: string, rightId: string): number {
  const left = asset.documents[leftId];
  const right = asset.documents[rightId];
  if (!left || !right) return leftId.localeCompare(rightId);
  return compareRankedDocuments({ id: leftId, ...left }, { id: rightId, ...right });
}

export function createInteractionIndex(asset: InteractionIndexAsset): InteractionIndex {
  const cardBySlug = new Map<string, number>();
  asset.cards.forEach((card, index) => {
    cardBySlug.set(card[0], index);
  });
  const documentsOfCard = new Map<number, string[]>();
  for (const [id, document] of Object.entries(asset.documents)) {
    for (const card of document.c) {
      const list = documentsOfCard.get(card);
      if (list) list.push(id);
      else documentsOfCard.set(card, [id]);
    }
  }
  for (const list of documentsOfCard.values()) {
    list.sort((left, right) => compareDocuments(asset, left, right));
  }
  const cardsOfSubstance = new Map<number, number[]>();
  asset.cards.forEach((card, index) => {
    for (const substance of card[2]) {
      const list = cardsOfSubstance.get(substance);
      if (list) list.push(index);
      else cardsOfSubstance.set(substance, [index]);
    }
  });
  return { asset, cardBySlug, documentsOfCard, cardsOfSubstance };
}

export interface IndexedSentence {
  readonly documentId: string;
  /** Full section id and the checksum of its canonical text. */
  readonly section: readonly [string, string];
  readonly start: number;
  readonly end: number;
  readonly flags: number;
  readonly targets: readonly number[];
}

/** Which targets of the index a drug is hit by: its substances and the classes its ATC codes fall in. */
export function drugTargetSet(index: InteractionIndex, cardIndex: number): ReadonlySet<number> {
  const card = index.asset.cards[cardIndex];
  const hit = new Set<number>(card?.[2] ?? []);
  if (!card) return hit;
  index.asset.targets.forEach((target, targetIndex) => {
    if (!target.startsWith('c:')) return;
    const code = target.slice(2);
    if (card[1].some((atc) => atc.startsWith(code))) hit.add(targetIndex);
  });
  return hit;
}

/** The sentences of `documentId` that name something in `targets`, in reading order. */
export function sentencesNaming(
  index: InteractionIndex,
  documentId: string,
  targets: ReadonlySet<number>,
): readonly IndexedSentence[] {
  const document = index.asset.documents[documentId];
  if (!document) return [];
  const sentences: IndexedSentence[] = [];
  for (const entry of document.sp) {
    const [section, start, end, flags, ...named] = entry as readonly number[];
    if (section === undefined || start === undefined || end === undefined || flags === undefined)
      continue;
    if (!named.some((target) => targets.has(target))) continue;
    const sectionEntry = document.sec[section];
    if (!sectionEntry) continue;
    sentences.push({
      documentId,
      section: [`${SECTION_ID_PREFIX}${sectionEntry[0]}`, sectionEntry[1]],
      start,
      end,
      flags,
      targets: named,
    });
  }
  return sentences;
}
