/**
 * The drug-comparison index asset (CMP1): its shape, its validation at the package boundary and the
 * lookups the tool and the search card use. Generated by `scripts/build-drug-comparison.ts`;
 * nobody edits it by hand.
 *
 * It holds NO instruction text. For every МНН card it holds the registry facts the comparison
 * shows as rows (ЕСКЛП: forms, strengths, ЖНВЛП, counts; ГРЛС: conditions of dispensing), and for
 * every instruction document of the modules a record of which quoted sections it has, so the tool
 * can choose the instruction to read before it is installed. The quoted text itself is always read
 * from the installed document, with that document's own provenance.
 */
import {
  INSTRUCTION_KINDS,
  type IndexedInstructionKind,
} from '@/features/drug-interactions/interaction-index';

export const COMPARISON_INDEX_SCHEMA_VERSION = 1;

/** Bits of `AssetDocument.y`: which quoted sections the instruction has, in `SECTION_ROWS` order. */
export const SECTION_BITS = {
  indications: 1 << 0,
  contraindications: 1 << 1,
  dosage: 1 << 2,
  adverse: 1 << 3,
  special: 1 << 4,
  overdose: 1 << 5,
  group: 1 << 6,
  dispensing: 1 << 7,
} as const;
/** The six quoted section rows (without the short group and dispensing lines). */
export const ROW_MASK = (1 << 6) - 1;

/** `essential` flags of a dosage form: some of its strengths are in the ЖНВЛП list / are not. */
export const ESSENTIAL_LISTED = 1;
export const ESSENTIAL_NOT_LISTED = 2;

/** `[dosage form index, strengths, essential flags]`. */
export type AssetForm = readonly [form: number, strengths: readonly string[], essential: number];

export interface AssetCard {
  /** Card id without «esklp.mnn.». */
  readonly s: string;
  /** The standardized МНН as the registry writes it. */
  readonly n: string;
  readonly a: readonly string[];
  /** Pharmacotherapeutic groups as the registry words them. */
  readonly g: readonly string[];
  readonly f: readonly AssetForm[];
  /** Distinct registration numbers, trade names, manufacturers and holders (ЕСКЛП). */
  readonly r: number;
  readonly t: number;
  readonly m: number;
  readonly h: number;
  /** Valid ГРЛС registrations of the card by conditions of dispensing: `[Rx, OTC, mixed, not stated]`. */
  readonly x: readonly [number, number, number, number] | null;
}

export interface AssetDocument {
  /** Indexes into `cards`. */
  readonly c: readonly number[];
  /** Index into `modules`. */
  readonly m: number;
  /** Trade name of the product, as the registry writes it. */
  readonly t: string | null;
  /** Index into `INSTRUCTION_KINDS`. */
  readonly k: number;
  /** 1 for a holder's own site, 0 for a ГРЛС file. */
  readonly s: 0 | 1;
  /** Index into `forms` of the document's dosage form; -1 when it has none. */
  readonly f: number;
  /** Bit mask of the quoted sections the instruction has (`SECTION_BITS`). */
  readonly y: number;
}

export interface ComparisonIndexAsset {
  readonly schemaVersion: typeof COMPARISON_INDEX_SCHEMA_VERSION;
  readonly basis: {
    readonly esklp: { readonly edition: string };
    readonly grls: { readonly edition: string };
    readonly modules: readonly {
      readonly id: string;
      readonly version: string;
      readonly sha256: string;
    }[];
  };
  readonly modules: readonly string[];
  /** Dosage form wordings, lower case. */
  readonly forms: readonly string[];
  readonly cards: readonly AssetCard[];
  readonly documents: Readonly<Record<string, AssetDocument>>;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function fail(message: string): never {
  throw new Error(`Drug-comparison index: ${message}`);
}

function isIndex(value: unknown, limit: number): value is number {
  return Number.isInteger(value) && (value as number) >= 0 && (value as number) < limit;
}

function isCount(value: unknown): value is number {
  return Number.isInteger(value) && (value as number) >= 0;
}

function stringList(value: unknown, what: string): readonly string[] {
  if (!Array.isArray(value) || value.some((item) => typeof item !== 'string')) {
    fail(`${what} is not a list of strings`);
  }
  return value as readonly string[];
}

function parseCard(value: unknown, formCount: number): AssetCard {
  if (!isRecord(value)) fail('a card is not an object');
  const { s, n, a, g, f, r, t, m, h, x } = value;
  if (typeof s !== 'string' || s === '') fail('a card has no id');
  if (typeof n !== 'string') fail(`card ${s} has no name`);
  if (![r, t, m, h].every(isCount)) fail(`card ${s} has a malformed count`);
  if (!Array.isArray(f)) fail(`card ${s} has no forms`);
  const forms = (f as readonly unknown[]).map((entry): AssetForm => {
    if (!Array.isArray(entry) || entry.length !== 3) fail(`card ${s} has a malformed form`);
    const [form, strengths, essential] = entry as readonly unknown[];
    if (!isIndex(form, formCount) || !isIndex(essential, 4)) fail(`card ${s} has a bad form index`);
    return [form, stringList(strengths, `card ${s} strengths`), essential];
  });
  if (x !== null && (!Array.isArray(x) || x.length !== 4 || x.some((item) => !isCount(item)))) {
    fail(`card ${s} has malformed dispensing counts`);
  }
  return {
    s,
    n,
    a: stringList(a, `card ${s} ATC codes`),
    g: stringList(g, `card ${s} groups`),
    f: forms,
    r: r as number,
    t: t as number,
    m: m as number,
    h: h as number,
    x: x as AssetCard['x'],
  };
}

function parseDocument(
  id: string,
  value: unknown,
  counts: { cards: number; modules: number; forms: number },
): AssetDocument {
  if (!isRecord(value)) fail(`document ${id} is not an object`);
  const { c, m, t, k, s, f, y } = value;
  if (!Array.isArray(c) || c.length === 0 || c.some((item) => !isIndex(item, counts.cards))) {
    fail(`document ${id} has an invalid card`);
  }
  if (!isIndex(m, counts.modules)) fail(`document ${id} has no module`);
  if (!isIndex(k, INSTRUCTION_KINDS.length)) fail(`document ${id} has an unknown kind`);
  if (s !== 0 && s !== 1) fail(`document ${id} has an unknown source class`);
  if (t !== null && typeof t !== 'string') fail(`document ${id} has an invalid trade name`);
  if (f !== -1 && !isIndex(f, counts.forms)) fail(`document ${id} has an invalid form`);
  if (!isCount(y)) fail(`document ${id} has no section mask`);
  return { c: c as readonly number[], m, t: t as string | null, k, s, f: f as number, y };
}

/** Checks the asset's shape once; a malformed asset is an error, never a silently empty index. */
export function parseComparisonIndex(value: unknown): ComparisonIndexAsset {
  if (!isRecord(value)) fail('not an object');
  if (value['schemaVersion'] !== COMPARISON_INDEX_SCHEMA_VERSION)
    fail('unsupported schema version');
  const { basis, modules, forms, cards, documents } = value;
  if (!isRecord(basis) || !isRecord(basis['esklp']) || !isRecord(basis['grls'])) {
    fail('basis is missing');
  }
  const esklp = basis['esklp'];
  const grls = basis['grls'];
  if (typeof esklp['edition'] !== 'string' || typeof grls['edition'] !== 'string') {
    fail('basis editions are missing');
  }
  const moduleList = stringList(modules, 'modules');
  const formList = stringList(forms, 'forms');
  if (!Array.isArray(cards)) fail('cards is not a list');
  if (!isRecord(documents)) fail('documents is not an object');
  const parsedCards = (cards as readonly unknown[]).map((card) => parseCard(card, formList.length));
  const counts = { cards: parsedCards.length, modules: moduleList.length, forms: formList.length };
  const parsedDocuments: Record<string, AssetDocument> = {};
  for (const [id, document] of Object.entries(documents)) {
    parsedDocuments[id] = parseDocument(id, document, counts);
  }
  const modulesBasis = basis['modules'];
  return {
    schemaVersion: COMPARISON_INDEX_SCHEMA_VERSION,
    basis: {
      esklp: { edition: esklp['edition'] },
      grls: { edition: grls['edition'] },
      modules: Array.isArray(modulesBasis)
        ? (modulesBasis as readonly { id: string; version: string; sha256: string }[])
        : [],
    },
    modules: moduleList,
    forms: formList,
    cards: parsedCards,
    documents: parsedDocuments,
  };
}

/** How many of the six quoted section rows an instruction has. */
export function rowCount(mask: number): number {
  let count = 0;
  for (let bit = 1; bit <= SECTION_BITS.overdose; bit <<= 1) if ((mask & bit) !== 0) count += 1;
  return count;
}

/** The first word of a dosage form («таблетки, покрытые оболочкой» → «таблетки»): its class. */
export function formClass(form: string | null | undefined): string {
  return form?.toLocaleLowerCase('ru-RU').match(/[а-яёa-z]+/u)?.[0] ?? '';
}

export interface RankedDocument {
  readonly id: string;
  readonly document: AssetDocument;
}

/**
 * Which instruction of a card to read first: the one with the most quoted sections, a ГРЛС file
 * before a holder's own site, a professional text (ОХЛП, instruction) before a leaflet. Pure and
 * stable: the same asset gives the same order.
 */
export function compareInstructions(left: RankedDocument, right: RankedDocument): number {
  return (
    rowCount(right.document.y) - rowCount(left.document.y) ||
    left.document.s - right.document.s ||
    left.document.k - right.document.k ||
    left.id.localeCompare(right.id)
  );
}

export interface ComparisonIndex {
  readonly asset: ComparisonIndexAsset;
  readonly cardBySlug: ReadonlyMap<string, number>;
  /** Card index → its instructions, best first. */
  readonly documentsOfCard: ReadonlyMap<number, readonly string[]>;
}

export function createComparisonIndex(asset: ComparisonIndexAsset): ComparisonIndex {
  const cardBySlug = new Map<string, number>();
  asset.cards.forEach((card, index) => {
    cardBySlug.set(card.s, index);
  });
  const documentsOfCard = new Map<number, string[]>();
  for (const [id, document] of Object.entries(asset.documents)) {
    for (const card of document.c) {
      const list = documentsOfCard.get(card);
      if (list) list.push(id);
      else documentsOfCard.set(card, [id]);
    }
  }
  for (const list of documentsOfCard.values()) {
    list.sort((left, right) => {
      const a = asset.documents[left];
      const b = asset.documents[right];
      if (!a || !b) return left.localeCompare(right);
      return compareInstructions({ id: left, document: a }, { id: right, document: b });
    });
  }
  return { asset, cardBySlug, documentsOfCard };
}

export function documentKind(document: AssetDocument): IndexedInstructionKind {
  return INSTRUCTION_KINDS[document.k] ?? 'unknown';
}
