import {
  type ContentModuleCatalogEntry,
  ContentModuleCatalogEntrySchema,
} from '@localmed/contracts';

// This file is generated by prepare-definition-reference.py, contains only a descriptor,
// and is ignored by Git. Source text remains in the optional SQLite file, never in JS.
const localDescriptors = import.meta.env.DEV
  ? import.meta.glob('./catalog.definition-reference.local.json', {
      eager: true,
      import: 'default',
    })
  : {};

export function withLocalDefinitionReference(
  modules: readonly ContentModuleCatalogEntry[],
): ContentModuleCatalogEntry[] {
  const result = [...modules];
  for (const raw of Object.values(localDescriptors)) {
    if (
      !raw ||
      typeof raw !== 'object' ||
      !('module' in raw) ||
      !('fileName' in raw) ||
      typeof raw.fileName !== 'string' ||
      !/^[a-z0-9.-]+\.db\.gz$/u.test(raw.fileName)
    ) {
      throw new Error('Invalid local reference descriptor. Rebuild the local edition.');
    }
    const module = ContentModuleCatalogEntrySchema.parse(raw.module);
    if (
      !module.definitionReference ||
      module.releaseState !== 'preview' ||
      module.artifacts.length !== 1 ||
      result.some((existing) => existing.id === module.id)
    ) {
      throw new Error('Conflicting local reference descriptor.');
    }
    const base = new URL(import.meta.env.BASE_URL, globalThis.location.href);
    const url = new URL(`content/definition-reference/${raw.fileName}`, base).href;
    result.push(
      ContentModuleCatalogEntrySchema.parse({
        ...module,
        artifacts: module.artifacts.map((artifact) => ({ ...artifact, url })),
      }),
    );
  }
  return result;
}
