import { type ContentModuleCatalogEntry, ContentModuleCatalogSchema } from '@localmed/contracts';

const compatibility = {
  minAppVersion: '0.3.1',
  maxAppVersion: null,
  schemaVersion: 2,
  coreCatalogVersion: '1',
} as const;

const unknownSizes = {
  downloadBytes: null,
  installedBytes: null,
  sourceAssetsDownloadBytes: null,
  precision: 'unknown' as const,
};

const clinicalCapabilities: ContentModuleCatalogEntry['capabilities'] = {
  search: true,
  fullText: true,
  structuredTables: true,
  images: true,
  originalPdf: true,
  structuredKnowledge: true,
  calculations: false,
};

function coreDependency() {
  return [{ moduleId: 'minimed.core.ru', versionRange: '^1.0.0', required: true }];
}

export const MODULE_CATALOG = ContentModuleCatalogSchema.parse({
  catalogVersion: '1-preview',
  channel: 'preview',
  publishedAt: '2026-07-21T00:00:00Z',
  modules: [
    {
      id: 'minimed.core.ru',
      version: '1.0.0-preview.1',
      kind: 'core',
      collection: 'core',
      title: 'Ядро MiniMed',
      description:
        'Глобальный каталог заболеваний, препаратов и документов, короткие проверяемые справки, алиасы, грубые связи и маршрутизация к незагруженным модулям.',
      required: true,
      releaseState: 'bundled',
      specialties: [],
      populations: ['all'],
      tags: ['catalog', 'routing', 'global-graph'],
      compatibility,
      sourceSetDigest: null,
      dependencies: [],
      sizes: {
        downloadBytes: 0,
        installedBytes: null,
        sourceAssetsDownloadBytes: null,
        precision: 'unknown',
      },
      capabilities: {
        search: true,
        fullText: false,
        structuredTables: false,
        images: false,
        originalPdf: false,
        structuredKnowledge: true,
        calculations: false,
      },
      artifacts: [],
      documents: [],
      previewDocumentCount: 15,
    },
    {
      id: 'minimed.clinical.pediatrics.general',
      version: '0.0.0-planned',
      kind: 'clinical',
      collection: 'pediatrics',
      title: 'Педиатрия: общая и первичная помощь',
      description:
        'Частые амбулаторные состояния, рост и развитие, синдромный поиск, профилактика и маршрутизация к профильным разделам.',
      required: false,
      releaseState: 'planned',
      specialties: ['pediatrics', 'general-practice'],
      populations: ['children'],
      tags: ['primary-care', 'common-conditions'],
      compatibility,
      sourceSetDigest: null,
      dependencies: coreDependency(),
      sizes: unknownSizes,
      capabilities: clinicalCapabilities,
      artifacts: [],
      documents: [],
      previewDocumentCount: 0,
    },
    {
      id: 'minimed.clinical.pediatrics.infectious',
      version: '0.3.1-preview',
      kind: 'clinical',
      collection: 'pediatrics',
      title: 'Педиатрия: инфекционные болезни',
      description:
        'Инфекционные заболевания детского возраста, эпидемиология, диагностика, лечение, изоляция и красные флаги.',
      required: false,
      releaseState: 'preview',
      specialties: ['pediatrics', 'infectious-diseases'],
      populations: ['children'],
      tags: ['infection', 'isolation'],
      compatibility,
      sourceSetDigest: null,
      dependencies: coreDependency(),
      sizes: unknownSizes,
      capabilities: clinicalCapabilities,
      artifacts: [],
      documents: [],
      previewDocumentCount: 3,
    },
    {
      id: 'minimed.clinical.pediatrics.respiratory-allergy',
      version: '0.3.1-preview',
      kind: 'clinical',
      collection: 'pediatrics',
      title: 'Педиатрия: дыхание и аллергология',
      description:
        'Болезни дыхательных путей, пульмонология, обструктивные состояния и аллергические заболевания.',
      required: false,
      releaseState: 'preview',
      specialties: ['pediatrics', 'pulmonology', 'allergy-immunology'],
      populations: ['children'],
      tags: ['respiratory', 'allergy'],
      compatibility,
      sourceSetDigest: null,
      dependencies: coreDependency(),
      sizes: unknownSizes,
      capabilities: clinicalCapabilities,
      artifacts: [],
      documents: [],
      previewDocumentCount: 3,
    },
    {
      id: 'minimed.clinical.pediatrics.gastro-nutrition',
      version: '0.0.0-planned',
      kind: 'clinical',
      collection: 'pediatrics',
      title: 'Педиатрия: гастроэнтерология и питание',
      description:
        'Заболевания ЖКТ и печени, питание, нарушения вскармливания, обезвоживание и нутритивная поддержка.',
      required: false,
      releaseState: 'planned',
      specialties: ['pediatrics', 'gastroenterology', 'nutrition'],
      populations: ['children'],
      tags: ['gastroenterology', 'nutrition'],
      compatibility,
      sourceSetDigest: null,
      dependencies: coreDependency(),
      sizes: unknownSizes,
      capabilities: clinicalCapabilities,
      artifacts: [],
      documents: [],
      previewDocumentCount: 0,
    },
    {
      id: 'minimed.clinical.pediatrics.nephro-urology',
      version: '0.3.1-preview',
      kind: 'clinical',
      collection: 'pediatrics',
      title: 'Педиатрия: нефрология и урология',
      description:
        'Инфекции мочевой системы, заболевания почек, водно-электролитные нарушения и урологическая маршрутизация.',
      required: false,
      releaseState: 'preview',
      specialties: ['pediatrics', 'nephrology', 'urology'],
      populations: ['children'],
      tags: ['kidney', 'urinary'],
      compatibility,
      sourceSetDigest: null,
      dependencies: coreDependency(),
      sizes: unknownSizes,
      capabilities: clinicalCapabilities,
      artifacts: [],
      documents: [],
      previewDocumentCount: 1,
    },
    {
      id: 'minimed.clinical.pediatrics.neuro-emergency',
      version: '0.0.0-planned',
      kind: 'clinical',
      collection: 'pediatrics',
      title: 'Педиатрия: неврология и неотложная помощь',
      description:
        'Неврологические состояния, судороги, нарушения сознания, неотложные алгоритмы и интенсивная помощь.',
      required: false,
      releaseState: 'planned',
      specialties: ['pediatrics', 'neurology', 'emergency-medicine'],
      populations: ['children'],
      tags: ['neurology', 'emergency'],
      compatibility,
      sourceSetDigest: null,
      dependencies: coreDependency(),
      sizes: unknownSizes,
      capabilities: clinicalCapabilities,
      artifacts: [],
      documents: [],
      previewDocumentCount: 0,
    },
    {
      id: 'minimed.clinical.pediatrics.surgery-trauma',
      version: '0.0.0-planned',
      kind: 'clinical',
      collection: 'pediatrics',
      title: 'Детская хирургия и травма',
      description:
        'Острые хирургические состояния, врождённые пороки, травма, послеоперационное ведение и маршрутизация.',
      required: false,
      releaseState: 'planned',
      specialties: ['pediatric-surgery', 'traumatology'],
      populations: ['children'],
      tags: ['surgery', 'trauma'],
      compatibility,
      sourceSetDigest: null,
      dependencies: coreDependency(),
      sizes: unknownSizes,
      capabilities: clinicalCapabilities,
      artifacts: [],
      documents: [],
      previewDocumentCount: 0,
    },
    {
      id: 'minimed.medications.ru',
      version: '0.3.1-preview',
      kind: 'medication',
      collection: 'shared',
      title: 'Лекарственные препараты РФ',
      description:
        'Официальная регистрационная идентичность и полные инструкции; дозы и показания становятся доверенными только после проверки.',
      required: false,
      releaseState: 'preview',
      specialties: [],
      populations: ['all'],
      tags: ['drugs', 'instructions', 'registry'],
      compatibility,
      sourceSetDigest: null,
      dependencies: coreDependency(),
      sizes: unknownSizes,
      capabilities: {
        ...clinicalCapabilities,
        images: false,
        calculations: false,
      },
      artifacts: [],
      documents: [],
      previewDocumentCount: 8,
    },
    {
      id: 'minimed.regulatory.pediatrics.ru',
      version: '0.3.1-preview',
      kind: 'regulatory',
      collection: 'shared',
      title: 'Нормативные документы РФ: педиатрия',
      description:
        'Действующие и исторические приказы, сроки, формы, маршрутизация и явные связи между редакциями.',
      required: false,
      releaseState: 'preview',
      specialties: ['pediatrics', 'health-administration'],
      populations: ['children'],
      tags: ['regulation', 'administration'],
      compatibility,
      sourceSetDigest: null,
      dependencies: coreDependency(),
      sizes: unknownSizes,
      capabilities: {
        ...clinicalCapabilities,
        calculations: false,
      },
      artifacts: [],
      documents: [],
      previewDocumentCount: 3,
    },
    {
      id: 'minimed.reference.pediatrics.ru',
      version: '0.0.0-planned',
      kind: 'reference',
      collection: 'shared',
      title: 'Диагностика, нормы и расчёты: педиатрия',
      description:
        'Возрастные нормы, лабораторные диапазоны, шкалы, формулы и детерминированные клинические калькуляторы.',
      required: false,
      releaseState: 'planned',
      specialties: ['pediatrics', 'laboratory-medicine'],
      populations: ['children'],
      tags: ['laboratory', 'reference', 'calculators'],
      compatibility,
      sourceSetDigest: null,
      dependencies: coreDependency(),
      sizes: unknownSizes,
      capabilities: {
        ...clinicalCapabilities,
        images: false,
        originalPdf: false,
        calculations: true,
      },
      artifacts: [],
      documents: [],
      previewDocumentCount: 0,
    },
  ],
});
