import { ContentModuleCatalogEntrySchema, ToolCatalogEntrySchema } from '@localmed/contracts';
import { z } from 'zod';

import rawShell from '@/features/modules/catalog.shell.json';
import type { ModuleCatalogShell } from '@/features/modules/module-catalog-shell-source';

// Generated by `bun run catalog:shell` from catalog.preview.json; a unit test keeps them equal.
const shell: ModuleCatalogShell = z
  .object({
    catalogVersion: z.string().min(1),
    publishedAt: z.string().min(1),
    coreModule: ContentModuleCatalogEntrySchema,
    sectionDocumentCounts: z.object({
      conditions: z.number().int().nonnegative(),
      guidelines: z.number().int().nonnegative(),
      medications: z.number().int().nonnegative(),
      legal: z.number().int().nonnegative(),
    }),
    tools: z.array(z.object({ moduleId: z.string().min(1), tool: ToolCatalogEntrySchema })),
  })
  .parse(rawShell);

const { coreModule } = shell;
if (!coreModule.sourceSetDigest || coreModule.sizes.installedBytes === null) {
  throw new Error('Bundled core catalog metadata is incomplete.');
}

export const BUNDLED_CORE_MODULE = {
  ...coreModule,
  sourceSetDigest: coreModule.sourceSetDigest,
  sizes: { ...coreModule.sizes, installedBytes: coreModule.sizes.installedBytes },
};

/** What each home section holds per the catalog: stable, whatever packs are installed. */
export const SECTION_DOCUMENT_COUNTS = shell.sectionDocumentCounts;

/** Always shipped with core discovery; these entries do not imply an installed tool payload. */
export const TOOL_CATALOG = shell.tools.map((entry) => entry.tool);

const moduleIdsByTool = new Map(shell.tools.map((entry) => [entry.tool.id, entry.moduleId]));

export function moduleIdForTool(toolId: string): string | undefined {
  return moduleIdsByTool.get(toolId);
}
