// Generated by scripts/generate-native-design-tokens.ts from apps/app/src/styles/theme.css and apps/app/src/styles/theme-dark.css.
// Do not edit: change the CSS and run `bun run native:tokens`.
// Not generated (no native value): --route-desk-gradient, --font-serif, --font-mono, --theme-type-response, --theme-primary-edge, --theme-primary-hover-background, --theme-primary-active-background, --theme-primary-rest-shadow, --theme-primary-hover-shadow, --theme-text-underline-offset, --theme-assessment-legend-padding, --page-grain-image, --masked-grain-image.
package dev.localmed.nativespike.shared.designsystem

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Immutable
data class NativeShadowLayer(
    val inset: Boolean,
    val x: Dp,
    val y: Dp,
    val blur: Dp,
    val spread: Dp,
    val color: Color,
)

/** CSS timing: duration plus the CSS easing keyword it was declared with. */
@Immutable
data class NativeMotion(val durationMillis: Int, val easing: String)

@Immutable
data class NativeColorTokens(
    val background: Color,
    val surface: Color,
    val surfaceRaised: Color,
    val surfaceMuted: Color,
    val border: Color,
    val text: Color,
    val textMuted: Color,
    val textFaint: Color,
    val accent: Color,
    val accentContrast: Color,
    val accentSoft: Color,
    val link: Color,
    val searchSurface: Color,
    val searchSurfaceMuted: Color,
    val floatingSurface: Color,
    val floatingBorder: Color,
    val floatingText: Color,
    val danger: Color,
    val kicker: Color,
    val personal: Color,
    val personalSoft: Color,
    val personalContrast: Color,
    val warning: Color,
    val warningSoft: Color,
    val matchBackground: Color,
    val matchText: Color,
    val info: Color,
    val infoSoft: Color,
    val note: Color,
    val edge: Color,
    val graphStroke: Color,
    val ink: Color,
    val inkSoft: Color,
    val inkFaint: Color,
    val paper: Color,
    val paperLight: Color,
    val paperDeep: Color,
    val paperLine: Color,
    val folder: Color,
    val folderLight: Color,
    val folderDark: Color,
    val desk: Color,
    val deskDark: Color,
    val stamp: Color,
    val stampFaded: Color,
    val bluePencil: Color,
    val greenFile: Color,
)

val LightColorTokens = NativeColorTokens(
    background = Color(0xFF777266),
    surface = Color(0xFFF3ECD9),
    surfaceRaised = Color(0xFFFBF7EA),
    surfaceMuted = Color(0xFFE6DCC4),
    border = Color(0xFFCBC0A7),
    text = Color(0xFF292720),
    textMuted = Color(0xFF585349),
    textFaint = Color(0xFF615B50),
    accent = Color(0xFF405B4E),
    accentContrast = Color(0xFFF8F0DD),
    accentSoft = Color(0x1F405B4E),
    link = Color(0xFF355B49),
    searchSurface = Color(0xFFF7EDCF),
    searchSurfaceMuted = Color(0xFFEADFBE),
    floatingSurface = Color(0xFF344D41),
    floatingBorder = Color(0xFF789083),
    floatingText = Color(0xFFFFF9E8),
    danger = Color(0xFF87453C),
    kicker = Color(0xFF87453C),
    personal = Color(0xFF925A78),
    personalSoft = Color(0xFFE6D8D3),
    personalContrast = Color(0xFFF6EEF5),
    warning = Color(0xFF75560F),
    warningSoft = Color(0xFFF2DFA3),
    matchBackground = Color(0xFFD9CD7A),
    matchText = Color(0xFF292720),
    info = Color(0xFF315F7A),
    infoSoft = Color(0xFFDBEAF3),
    note = Color(0xFFF2E6C2),
    edge = Color(0xFFCBC0A7),
    graphStroke = Color(0xFF615B50),
    ink = Color(0xFF292720),
    inkSoft = Color(0xFF585349),
    inkFaint = Color(0xFF615B50),
    paper = Color(0xFFF3ECD9),
    paperLight = Color(0xFFFBF7EA),
    paperDeep = Color(0xFFE6DCC4),
    paperLine = Color(0xFFCBC0A7),
    folder = Color(0xFFB9A06A),
    folderLight = Color(0xFFCBB37C),
    folderDark = Color(0xFF8F7849),
    desk = Color(0xFF777266),
    deskDark = Color(0xFF5C584F),
    stamp = Color(0xFF87453C),
    stampFaded = Color(0x2487453C),
    bluePencil = Color(0xFF405B4E),
    greenFile = Color(0xFF405B4E),
)

val DarkColorTokens = NativeColorTokens(
    background = Color(0xFF211B17),
    surface = Color(0xFF2D2721),
    surfaceRaised = Color(0xFF372E26),
    surfaceMuted = Color(0xFF251F1A),
    border = Color(0xFF594735),
    text = Color(0xFFEEE5D4),
    textMuted = Color(0xFFC8BCA8),
    textFaint = Color(0xFFB5A88F),
    accent = Color(0xFF82A88D),
    accentContrast = Color(0xFF1C1712),
    accentSoft = Color(0x2682A88D),
    link = Color(0xFF9BC7A7),
    searchSurface = Color(0xFF243029),
    searchSurfaceMuted = Color(0xFF2C3A31),
    floatingSurface = Color(0xFF456452),
    floatingBorder = Color(0xFF78947F),
    floatingText = Color(0xFFFFF9E8),
    danger = Color(0xFFD98578),
    kicker = Color(0xFFD98578),
    personal = Color(0xFF925A78),
    personalSoft = Color(0xFF3B2E2D),
    personalContrast = Color(0xFFF6EEF5),
    warning = Color(0xFFF0CD71),
    warningSoft = Color(0xFF857146),
    matchBackground = Color(0xFF665324),
    matchText = Color(0xFFFFF5DC),
    info = Color(0xFF91C4E4),
    infoSoft = Color(0x2991C4E4),
    note = Color(0xFF302D25),
    edge = Color(0xFF594735),
    graphStroke = Color(0xFFC4A882),
    ink = Color(0xFFEEE5D4),
    inkSoft = Color(0xFFC8BCA8),
    inkFaint = Color(0xFFB5A88F),
    paper = Color(0xFF2D2721),
    paperLight = Color(0xFF372E26),
    paperDeep = Color(0xFF251F1A),
    paperLine = Color(0xFF594735),
    folder = Color(0xFF2E261F),
    folderLight = Color(0xFF342C23),
    folderDark = Color(0xFF2A241E),
    desk = Color(0xFF211B17),
    deskDark = Color(0xFF16120D),
    stamp = Color(0xFFD98578),
    stampFaded = Color(0x26D98578),
    bluePencil = Color(0xFF82A88D),
    greenFile = Color(0xFF82A88D),
)

@Immutable
data class NativeShadowTokens(
    val controlHoverShadow: List<NativeShadowLayer>,
    val cardHoverShadow: List<NativeShadowLayer>,
    val shadowPaper: List<NativeShadowLayer>,
    val shadowFolder: List<NativeShadowLayer>,
    val primaryActiveShadow: List<NativeShadowLayer>,
)

val LightShadowTokens = NativeShadowTokens(
    controlHoverShadow = listOf(
        NativeShadowLayer(inset = false, x = 0.dp, y = 4.dp, blur = 12.dp, spread = 0.dp, color = Color(0x2E292319)),
    ),
    cardHoverShadow = listOf(
        NativeShadowLayer(inset = true, x = 0.dp, y = 1.dp, blur = 0.dp, spread = 0.dp, color = Color(0xBFFFFFFF)),
        NativeShadowLayer(inset = false, x = 0.dp, y = 24.dp, blur = 48.dp, spread = 0.dp, color = Color(0x42221F19)),
    ),
    shadowPaper = listOf(
        NativeShadowLayer(inset = true, x = 0.dp, y = 1.dp, blur = 0.dp, spread = 0.dp, color = Color(0xBFFFFFFF)),
        NativeShadowLayer(inset = false, x = 0.dp, y = 22.dp, blur = 46.dp, spread = 0.dp, color = Color(0x33221F19)),
    ),
    shadowFolder = listOf(
        NativeShadowLayer(inset = false, x = 0.dp, y = 26.dp, blur = 65.dp, spread = 0.dp, color = Color(0x3D242018)),
    ),
    primaryActiveShadow = listOf(
        NativeShadowLayer(inset = true, x = 0.dp, y = 3.2.dp, blur = 6.4.dp, spread = 0.dp, color = Color(0x61000000)),
        NativeShadowLayer(inset = true, x = 0.dp, y = 0.dp, blur = 0.dp, spread = 1.dp, color = Color(0x24000000)),
    ),
)

val DarkShadowTokens = NativeShadowTokens(
    controlHoverShadow = listOf(
        NativeShadowLayer(inset = true, x = 0.dp, y = 0.8.dp, blur = 0.dp, spread = 0.dp, color = Color(0x14FFFFFF)),
        NativeShadowLayer(inset = true, x = 0.dp, y = -1.28.dp, blur = 0.dp, spread = 0.dp, color = Color(0x24000000)),
        NativeShadowLayer(inset = false, x = 0.dp, y = 2.56.dp, blur = 4.8.dp, spread = 0.dp, color = Color(0x52000000)),
        NativeShadowLayer(inset = false, x = 0.dp, y = 8.dp, blur = 16.dp, spread = 0.dp, color = Color(0x3D000000)),
    ),
    cardHoverShadow = listOf(
        NativeShadowLayer(inset = true, x = 0.dp, y = 1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x0FFFFFFF)),
        NativeShadowLayer(inset = false, x = 0.dp, y = 2.dp, blur = 4.8.dp, spread = 0.dp, color = Color(0x38000000)),
        NativeShadowLayer(inset = false, x = 0.dp, y = 24.dp, blur = 48.dp, spread = 0.dp, color = Color(0x66000000)),
    ),
    shadowPaper = listOf(
        NativeShadowLayer(inset = true, x = 0.dp, y = 1.dp, blur = 0.dp, spread = 0.dp, color = Color(0x0DFFFFFF)),
        NativeShadowLayer(inset = false, x = 0.dp, y = 4.dp, blur = 12.dp, spread = 0.dp, color = Color(0x33000000)),
        NativeShadowLayer(inset = false, x = 0.dp, y = 22.dp, blur = 46.dp, spread = 0.dp, color = Color(0x4D000000)),
    ),
    shadowFolder = listOf(
        NativeShadowLayer(inset = false, x = 0.dp, y = 4.dp, blur = 12.dp, spread = 0.dp, color = Color(0x3D000000)),
        NativeShadowLayer(inset = false, x = 0.dp, y = 26.dp, blur = 65.dp, spread = 0.dp, color = Color(0x61000000)),
    ),
    primaryActiveShadow = listOf(
        NativeShadowLayer(inset = true, x = 0.dp, y = 3.2.dp, blur = 6.4.dp, spread = 0.dp, color = Color(0x80000000)),
        NativeShadowLayer(inset = true, x = 0.dp, y = 0.dp, blur = 0.dp, spread = 1.dp, color = Color(0x40000000)),
    ),
)

/** Theme-independent lengths from theme.css (1 rem = 16 dp). */
object NativeDimensions {
    val space1 = 4.dp
    val space2 = 8.dp
    val space3 = 12.dp
    val space4 = 16.dp
    val space5 = 20.dp
    val spaceControl = 14.4.dp
    val spaceBodyGap = 11.2.dp
    val spaceFloatingInline = 20.dp
    val radiusControl = 8.8.dp
    val radiusPanel = 11.2.dp
    val borderHairline = 1.dp
    val outlineWidth = 2.dp
    val outlineOffset = 3.dp
    val outlineTightOffset = 1.dp
    val controlHeightLarge = 56.dp
    val controlIconSize = 33.6.dp
    val iconSizeSmall = 17.6.dp
    val iconSizeMethodology = 18.4.dp
    val assessmentResponseHeight = 88.dp
    val assessmentFloatingSize = 52.dp
    val assessmentFloatingOffset = 10.dp
    val assessmentScrollTopOffset = 72.dp
    val bottomNavClearance = 72.dp
    val bottomNavSecondaryClearance = 136.dp
    val assessmentResponseSafeSpace = 52.dp
    val assessmentLegendOverlap = -28.8.dp
}

object NativeTypeSizes {
    val typeMicro = 11.sp
    val typeLabel = 11.sp
    val typeFieldLabel = 12.48.sp
    val typeCaption = 12.sp
}

object NativeFontWeights {
    val weightLabel = FontWeight(700)
    val weightEmphasis = FontWeight(750)
    val weightStrong = FontWeight(800)
}

object NativeMotionTokens {
    val motionControl = NativeMotion(durationMillis = 140, easing = "ease-out")
    val motionStandard = NativeMotion(durationMillis = 180, easing = "ease")
}
