import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const sourceDirectory = resolve(root, 'schema/sql');
const targetPath = resolve(root, 'packages/storage-sqlite/src/generated/schema.ts');
const sourceFiles = (await readdir(sourceDirectory))
  .filter((fileName) => /^\d+_.+\.sql$/.test(fileName))
  .toSorted();
if (sourceFiles.length === 0) throw new Error('No SQLite schema files were found.');
const sources = await Promise.all(
  sourceFiles.map(async (fileName) => ({
    fileName,
    source: await readFile(resolve(sourceDirectory, fileName), 'utf8'),
  })),
);
const combined = sources
  .map(({ fileName, source }) => `-- ${fileName}\n${source.trim()}\n`)
  .join('\n');
await mkdir(resolve(targetPath, '..'), { recursive: true });
const generated = `// Generated by scripts/generate-schema.mjs. Do not edit manually.\nexport const SCHEMA_SQL = ${JSON.stringify(combined)};\n`;

if (process.argv.includes('--check')) {
  const existing = await readFile(targetPath, 'utf8').catch(() => '');
  if (existing !== generated) {
    process.stderr.write('Generated SQLite schema is stale. Run bun run schema:generate.\n');
    process.exitCode = 1;
  }
} else {
  await writeFile(targetPath, generated, 'utf8');
}
