import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const source = await readFile(resolve(root, 'apps/app/src/components/AppGlyph.tsx'), 'utf8');
const imports = new Map(
  [...source.matchAll(/^import (\w+) from '@phosphor-icons\/core\/([^']+)\?raw';$/gm)].map(
    (match) => [match[1], `@phosphor-icons/core/${match[2]}`],
  ),
);
const glyphs: string[] = [];
for (const match of source.matchAll(/^ {2}(?:'([^']+)'|(\w+)): svgBody\((\w+)\),$/gm)) {
  const name = match[1] ?? match[2];
  const dependency = imports.get(match[3]);
  if (!dependency) throw new Error(`Unknown icon source: ${name}`);
  const svg = await readFile(Bun.resolveSync(dependency, resolve(root, 'apps/app')), 'utf8');
  if (!svg.includes('viewBox="0 0 256 256"')) throw new Error(`Unexpected icon viewport: ${name}`);
  if (/<(?:circle|rect|line|polyline|polygon|ellipse|g|use)\b/.test(svg)) {
    throw new Error(`Unprojected SVG primitive: ${name}`);
  }
  const paths = [...svg.matchAll(/<path\b([^>]+)\/?\s*>/g)].map((path) => {
    const data = path[1].match(/\bd="([^"]+)"/)?.[1];
    if (!data || !/^[a-zA-Z0-9\s.,+-]+$/.test(data)) throw new Error(`Invalid path: ${name}`);
    const evenOdd = /fill-rule="evenodd"/.test(path[1]);
    return `NativeGlyphPath(${JSON.stringify(data)}, ${evenOdd})`;
  });
  if (paths.length === 0) throw new Error(`Empty icon: ${name}`);
  const identifier = name
    .split('-')
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
  glyphs.push(`    ${identifier}(${JSON.stringify(name)}, listOf(${paths.join(', ')}))`);
}
if (glyphs.length < 100) throw new Error('Incomplete WebView icon registry');
const generated = `// Generated by scripts/prepare-native-icons.ts from the actual WebView AppGlyph registry.
// Phosphor Icons, MIT; licence: commonMain/composeResources/files/phosphor-icons-LICENSE.txt.
package dev.localmed.nativespike.shared.ui

internal data class NativeGlyphPath(val data: String, val evenOdd: Boolean)
enum class NativeAppGlyphName(val webName: String, internal val paths: List<NativeGlyphPath>) {
${glyphs.join(',\n')};
}
`;
const targets = [
  [
    'native/shared/src/commonMain/kotlin/dev/localmed/nativespike/shared/ui/NativeAppGlyphName.kt',
    generated,
  ],
  [
    'native/shared/src/commonMain/composeResources/files/phosphor-icons-LICENSE.txt',
    await readFile(resolve(root, 'node_modules/@phosphor-icons/core/LICENSE'), 'utf8'),
  ],
] as const;
for (const [path, expected] of targets) {
  if (process.argv.includes('--check')) {
    if ((await readFile(resolve(root, path), 'utf8')) !== expected)
      throw new Error(`WebView icon projection is stale: ${path}`);
  } else await writeFile(resolve(root, path), expected);
}
console.log(
  JSON.stringify({ icons: glyphs.length, source: 'WebView AppGlyph', dependenciesAdded: 0 }),
);
