import type { MedicationInteractionKnowledgeBase } from '@/features/interactions/interaction-types';

export const MEDICATION_INTERACTION_KNOWLEDGE: MedicationInteractionKnowledgeBase = {
  schemaVersion: 1,
  classes: [
    { id: 'class.maoi', title: 'Ингибиторы моноаминоксидазы' },
    { id: 'class.ssri', title: 'Селективные ингибиторы обратного захвата серотонина' },
    { id: 'class.gi-motility-increasing', title: 'Средства, повышающие моторику ЖКТ' },
  ],
  medications: [
    {
      id: 'med.escitalopram',
      preferredName: 'Эсциталопрам',
      aliases: ['escitalopram', 'эсциталопрама оксалат', 'lexapro', 'ципралекс'],
      classes: ['class.ssri'],
      externalIds: { atc: 'N06AB10' },
    },
    {
      id: 'med.fosfomycin',
      preferredName: 'Фосфомицин',
      aliases: ['fosfomycin', 'фосфомицина трометамол', 'fosfomycin tromethamine', 'монурал'],
      classes: [],
      externalIds: { atc: 'J01XX01' },
    },
    {
      id: 'med.linezolid',
      preferredName: 'Линезолид',
      aliases: ['linezolid', 'зивокс'],
      classes: ['class.maoi'],
      externalIds: { atc: 'J01XX08' },
    },
    {
      id: 'med.pimozide',
      preferredName: 'Пимозид',
      aliases: ['pimozide', 'орап'],
      classes: [],
      externalIds: { atc: 'N05AG02' },
    },
    {
      id: 'med.metoclopramide',
      preferredName: 'Метоклопрамид',
      aliases: ['metoclopramide', 'церукал'],
      classes: ['class.gi-motility-increasing'],
      externalIds: { atc: 'A03FA01' },
    },
    {
      id: 'med.cimetidine',
      preferredName: 'Циметидин',
      aliases: ['cimetidine'],
      classes: [],
      externalIds: { atc: 'A02BA01' },
    },
  ],
  assertions: [
    {
      id: 'interaction.escitalopram.maoi',
      subjectMedicationId: 'med.escitalopram',
      interactant: { kind: 'class', id: 'class.maoi' },
      direction: 'bidirectional',
      conclusion: 'contraindicated',
      severity: 'critical',
      certainty: 'established',
      interactionType: 'pharmacodynamic',
      mechanism: 'Суммарное усиление серотонинергической передачи при ингибировании МАО.',
      effect: 'Повышенный риск серотонинового синдрома.',
      recommendation:
        'Совместное применение противопоказано. Учитывайте требуемые инструкцией интервалы отмены.',
      evidenceIds: ['evidence.escitalopram.maoi'],
      reviewStatus: 'reviewed',
      reviewedAt: '2026-08-04',
    },
    {
      id: 'interaction.escitalopram.pimozide',
      subjectMedicationId: 'med.escitalopram',
      interactant: { kind: 'medication', id: 'med.pimozide' },
      direction: 'bidirectional',
      conclusion: 'contraindicated',
      severity: 'critical',
      certainty: 'established',
      interactionType: 'pharmacodynamic',
      mechanism: 'Риск увеличения экспозиции пимозида и удлинения интервала QT.',
      effect: 'Повышенный риск желудочковых аритмий.',
      recommendation: 'Совместное применение противопоказано.',
      evidenceIds: ['evidence.escitalopram.pimozide'],
      reviewStatus: 'reviewed',
      reviewedAt: '2026-08-04',
    },
    {
      id: 'interaction.fosfomycin.metoclopramide',
      subjectMedicationId: 'med.fosfomycin',
      interactant: { kind: 'medication', id: 'med.metoclopramide' },
      direction: 'subject-affects-interactant',
      conclusion: 'management-required',
      severity: 'moderate',
      certainty: 'established',
      interactionType: 'pharmacokinetic',
      mechanism: 'Ускорение моторики ЖКТ уменьшает системную и мочевую экспозицию фосфомицина.',
      effect: 'Возможное снижение эффективности фосфомицина.',
      recommendation:
        'Оцените необходимость метоклопрамида и возможную альтернативу; не считайте комбинацию нейтральной.',
      evidenceIds: ['evidence.fosfomycin.metoclopramide'],
      reviewStatus: 'reviewed',
      reviewedAt: '2026-08-04',
    },
    {
      id: 'interaction.fosfomycin.cimetidine',
      subjectMedicationId: 'med.fosfomycin',
      interactant: { kind: 'medication', id: 'med.cimetidine' },
      direction: 'bidirectional',
      conclusion: 'documented-no-significant-interaction',
      severity: 'none',
      certainty: 'established',
      interactionType: 'pharmacokinetic',
      mechanism: 'В официальной маркировке не выявлено влияния на фармакокинетику фосфомицина.',
      effect: 'Клинически значимого фармакокинетического изменения не показано.',
      recommendation:
        'По проверенному источнику специальная коррекция из-за этой пары не требуется.',
      evidenceIds: ['evidence.fosfomycin.cimetidine'],
      reviewStatus: 'reviewed',
      reviewedAt: '2026-08-04',
    },
  ],
  evidence: [
    {
      id: 'evidence.escitalopram.maoi',
      sourceTitle: 'DailyMed — Escitalopram tablets, section 7 Drug Interactions',
      sourceUrl:
        'https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=7d924d16-8a10-411d-be57-97c450f56de7&type=display',
      sourceType: 'official-label',
      sourceVersion: 'DailyMed label reviewed 2026-08-04',
      quote:
        'Escitalopram is contraindicated in patients taking MAOIs, including MAOIs such as linezolid.',
    },
    {
      id: 'evidence.escitalopram.pimozide',
      sourceTitle: 'DailyMed — Escitalopram tablets, section 7 Drug Interactions',
      sourceUrl:
        'https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=7d924d16-8a10-411d-be57-97c450f56de7&type=display',
      sourceType: 'official-label',
      sourceVersion: 'DailyMed label reviewed 2026-08-04',
      quote: 'Escitalopram is contraindicated in patients taking pimozide.',
    },
    {
      id: 'evidence.fosfomycin.metoclopramide',
      sourceTitle: 'DailyMed — Fosfomycin tromethamine, Drug Interactions',
      sourceUrl:
        'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6b9167a9-80e9-44e1-a609-c3eb78960acf',
      sourceType: 'official-label',
      sourceVersion: 'DailyMed label reviewed 2026-08-04',
      quote:
        'Metoclopramide lowers the serum concentration and urinary excretion of fosfomycin.',
    },
    {
      id: 'evidence.fosfomycin.cimetidine',
      sourceTitle: 'DailyMed — Fosfomycin tromethamine, Drug Interactions',
      sourceUrl:
        'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6b9167a9-80e9-44e1-a609-c3eb78960acf',
      sourceType: 'official-label',
      sourceVersion: 'DailyMed label reviewed 2026-08-04',
      quote: 'Cimetidine does not affect the pharmacokinetics of fosfomycin.',
    },
  ],
};
