package dev.localmed.nativespike.shared.golden

/**
 * Reads a value the Gradle test task supplied to this test process — a system property on the JVM
 * (desktop and Android unit tests both run on a plain host JVM classloader) or an environment
 * variable on iOS (the simulator only forwards `SIMCTL_CHILD_`-prefixed vars to the spawned test
 * process — see shared/build.gradle.kts and the iOS actual for why). Returns `null`, not a
 * hardcoded default, when the Gradle task never set it; callers decide whether that is fatal.
 * wasmJs: not implemented (see `readFileAtPath`'s doc for why) — its actual always returns `null`.
 */
expect fun readTestEnvironmentValue(name: String): String?

/**
 * Reads one file's full text by absolute path. One `expect`, one `actual` per platform family,
 * because "read a file MiniMed's own test resources checked in" means something different on each:
 *  - JVM (desktop) and Android unit tests both run on a plain JVM classloader, so they share one
 *    `actual` (the `jvmClasspathTest` intermediate source set, shared/build.gradle.kts) that reads
 *    it via `java.io.File`.
 *  - iOS has no JVM classpath; reads via plain POSIX `fopen`/`fread` rather than
 *    `NSString(contentsOfFile:)`, to avoid depending on the exact Kotlin/Native Foundation-interop
 *    signature for that factory method.
 *  - wasmJs: not implemented — loading a file into a Karma-run browser test needs either a
 *    `fetch()` (async, awkward from a sync `expect fun`) or a webpack copy-plugin step, neither set
 *    up for this spike; the `actual` throws a clear, honest "not verified on wasmJs" error instead
 *    of silently returning empty/fake data.
 */
expect fun readFileAtPath(path: String): String

private fun requireTestEnvironmentValue(name: String): String =
    readTestEnvironmentValue(name)
        ?: error(
            "$name was not supplied to this test process — the Gradle test task must set it " +
                "(see shared/build.gradle.kts, tasks.withType<Test>).",
        )

/** Absolute path to the directory holding `search-golden.json` and sibling JSON test fixtures
 * (`native/shared/src/commonTest/resources/`). */
private fun testResourceDir(): String = requireTestEnvironmentValue("TEST_RESOURCE_DIR")

/** Absolute path to the released `core.db` (`apps/app/public/content/core.db`) the golden fixtures
 * were exported from — same file, checked by `search-golden.json`'s own `coreDbSha256`. */
fun testCoreDbPath(): String = requireTestEnvironmentValue("CORE_DB_PATH")

/** One file under `commonTest/resources/`, by name, read identically on every verified platform. */
fun readTestResource(fileName: String): String = readFileAtPath("${testResourceDir()}/$fileName")

/** `search-golden.json`, generated by `tools/benchmarks/src/export-search-golden.ts --corpus=core`. */
fun readGoldenFixture(): String = readTestResource("search-golden.json")

/** `rapidfuzz-parity.fixture.json`, copied verbatim from
 * `packages/search-lexical/src/rapidfuzz-parity.fixture.json` (RapidFuzz 3.14.6 Python reference
 * values) — checks the Kotlin port of `rapidfuzz.ts`'s OSA/Levenshtein distance metrics
 * (`lexical/RapidFuzz.kt`). */
fun readRapidfuzzParityFixture(): String = readTestResource("rapidfuzz-parity.fixture.json")
